import type { Artifact } from "./artifact.types";

export const artifacts = [
  {
    id: "001",
    slug: "block-orbit",
    title: "Block Orbit",
    description: "A spatial image composition that rotates through layered depth.",
    category: "Spatial Motion",
    origin: "Toby & Tye",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#e5e0d6", foreground: "#191916", accent: "#ef5b37" },
  },
  {
    id: "002",
    slug: "split-menu",
    title: "Split Menu",
    description: "A full-screen menu built around expanding cards and directional movement.",
    category: "Navigation",
    origin: "Toby & Tye",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d9d3c7", foreground: "#171715", accent: "#d7472d" },
  },
  {
    id: "003",
    slug: "scroll-cinema",
    title: "Scroll Cinema",
    description: "A contained video that expands into an immersive viewing experience.",
    category: "Scroll",
    origin: "Toby & Tye",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#cbc7bd", foreground: "#161615", accent: "#ee5b35" },
  },
  {
    id: "004",
    slug: "ambient-artwork",
    title: "Ambient Artwork",
    description: "Album artwork that responds to the pointer through movement and depth.",
    category: "Pointer Motion",
    origin: "Spotify Now Playing",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d8d1c5", foreground: "#161615", accent: "#e35031" },
  },
  {
    id: "005",
    slug: "palette-shift",
    title: "Palette Shift",
    description: "An interface atmosphere that changes with colours extracted from artwork.",
    category: "Colour System",
    origin: "Spotify Now Playing",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#ddd7ca", foreground: "#181714", accent: "#ee5c36" },
  },
  {
    id: "006",
    slug: "track-transition",
    title: "Track Transition",
    description: "A coordinated transition between artwork, metadata and playback states.",
    category: "State Motion",
    origin: "Spotify Now Playing",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d2cdc2", foreground: "#171614", accent: "#e65032" },
  },
] as const satisfies readonly Artifact[];
