import type { Artifact } from "./artifact.types";

export const artifacts = [
  {
    id: "001",
    slug: "block-orbit",
    title: "Block Orbit",
    description: "A spatial image composition that rotates through layered depth.",
    category: "Spatial Motion",
    origin: "Personal identity study",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#e5e0d6", foreground: "#191916", accent: "#ef5b37" },
  },
  {
    id: "002",
    slug: "split-menu",
    title: "Split Menu",
    description: "A full-screen menu built around expanding cards and directional movement.",
    category: "Navigation",
    origin: "Toby & Tye",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d9d3c7", foreground: "#171715", accent: "#d7472d" },
  },
  {
    id: "003",
    slug: "three-image-orbit",
    title: "Three Image Orbit",
    description: "Three images move through a shared depth-aware orbit, shifting scale and hierarchy as they pass through space.",
    category: "SPATIAL MOTION",
    origin: "Personal identity study",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#e5e0d6", foreground: "#191916", accent: "#ef5b37" },
  },
  {
    id: "004",
    slug: "scroll-cinema",
    title: "Scroll Cinema",
    description: "A contained video that expands into an immersive viewing experience.",
    category: "Scroll",
    origin: "Personal motion study",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#cbc7bd", foreground: "#161615", accent: "#ee5b35" },
  },
  {
    id: "005",
    slug: "ambient-artwork",
    title: "Ambient Artwork",
    description: "Album artwork that responds to the pointer through movement and depth.",
    category: "Pointer Motion",
    origin: "Spotify Now Playing",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d8d1c5", foreground: "#161615", accent: "#e35031" },
  },
  {
    id: "006",
    slug: "palette-shift",
    title: "Palette Shift",
    description: "An interface atmosphere that changes with colours extracted from artwork.",
    category: "Colour System",
    origin: "Spotify Now Playing",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#ddd7ca", foreground: "#181714", accent: "#ee5c36" },
  },
  {
    id: "007",
    slug: "track-transition",
    title: "Track Transition",
    description: "A coordinated transition between artwork, metadata and playback states.",
    category: "State Motion",
    origin: "Spotify Now Playing",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d2cdc2", foreground: "#171614", accent: "#e65032" },
  },
  {
    id: "008",
    slug: "spatial-services",
    title: "Spatial Services",
    description: "An editorial service selector where navigation and imagery respond as a single spatial interface.",
    category: "Timed Tabs",
    origin: "Spatial systems study",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d8d3c8", foreground: "#171714", accent: "#df5134" },
  },
  {
    id: "009",
    slug: "scroll-sequence",
    title: "Scroll Sequence",
    description: "A scroll-driven sequence where viewport position synchronizes a rolling index, title and accumulating progress.",
    category: "Scroll State",
    origin: "Ace Trail",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#ddd8ce", foreground: "#171714", accent: "#e05232" },
  },
  {
    id: "010",
    slug: "card-flip",
    title: "Card Flip",
    description: "Relational hover states meet an accessible perspective-based front-to-back reveal.",
    category: "Card Motion",
    origin: "Ace Trail",
    year: 2026,
    status: "Published",
    featured: true,
    theme: { background: "#d8d3c8", foreground: "#171714", accent: "#df5134" },
  },
] as const satisfies readonly Artifact[];
